  version: "3"

  services:
    MYSQL_A:
      image: mysql:8.0
      container_name: MYSQL_A
      command: --server-id=1 --log-bin=mysql-bin --binlog-format=row --default-authentication-plugin=mysql_native_password #--binlog-do-db=todo_app Solo para indicar la DB
      ports: 
        - 3308:3306
      environment: 
        MYSQL_ROOT_PASSWORD: "root"
      volumes: 
        - ./schemas_a:/var/lib/mysql

    MYSQL_B:
      image: mysql:8.0
      container_name: MYSQL_B
      command: --server-id=2 --log-bin=mysql-bin --binlog-format=row --default-authentication-plugin=mysql_native_password #--binlog-do-db=todo_app Solo para indicar la DB
      ports: 
        - 3309:3306
      environment: 
        MYSQL_ROOT_PASSWORD: "root"
      volumes: 
        - ./schemas_b:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_HOSTS: MYSQL_A,MYSQL_B
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 9090:80
      depends_on:
        - MYSQL_A
        - MYSQL_B


  # docker-compose up -d

#   --- SCRIPT MASTER-SLAVE-MYSQL:

  # docker exec -it MYSQL_A mysql -u root -p

  # CREATE USER 'replicator'@'%' IDENTIFIED BY '1234';
  # GRANT ALL PRIVILEGES ON *.* TO 'replicator'@'%' WITH GRANT OPTION;
  # FLUSH PRIVILEGES;
  
  # SHOW GRANTS FOR 'replicator'@'%';
  
  # docker exec -it MYSQL_B mysql -u root -p
  
  # CHANGE MASTER TO
  # MASTER_HOST='MYSQL_A',
  # MASTER_USER='replicator',
  # MASTER_PASSWORD='1234',
  # MASTER_LOG_FILE='mysql-bin.000003',
  # MASTER_LOG_POS=854;
  
  # START SLAVE;
  # SHOW SLAVE STATUS\G;


# -- PRUEBA MYSQL_A
# CREATE DATABASE test_db;
# USE test_db;
# CREATE TABLE test_table (
#     id INT PRIMARY KEY,
#     name VARCHAR(50)
# );
# INSERT INTO test_table (id, name) VALUES (1, 'Prueba');


# -- Ver en MYSQL_B
# USE test_db;
# SELECT * FROM test_table;

